USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRADE_PIPELINE_ROLE;

CREATE WAREHOUSE IF NOT EXISTS TRADE_WH
  WAREHOUSE_SIZE='XSMALL'
  AUTO_SUSPEND=60
  AUTO_RESUME=TRUE
  INITIALLY_SUSPENDED=TRUE;

CREATE DATABASE IF NOT EXISTS TRADE_DB;

CREATE SCHEMA IF NOT EXISTS TRADE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS TRADE_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS TRADE_DB.AUDIT;
CREATE SCHEMA IF NOT EXISTS TRADE_DB.MONITORING;

GRANT USAGE ON WAREHOUSE TRADE_WH
TO ROLE TRADE_PIPELINE_ROLE;

GRANT USAGE ON DATABASE TRADE_DB
TO ROLE TRADE_PIPELINE_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE STREAM, CREATE TASK
ON ALL SCHEMAS IN DATABASE TRADE_DB
TO ROLE TRADE_PIPELINE_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN DATABASE TRADE_DB
TO ROLE TRADE_PIPELINE_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN DATABASE TRADE_DB
TO ROLE TRADE_PIPELINE_ROLE;

GRANT CREATE SCHEMA ON DATABASE TRADE_DB
TO ROLE TRADE_PIPELINE_ROLE;

-- Required so the user can activate TRADE_PIPELINE_ROLE.
-- Replace this placeholder with your Snowflake username.
GRANT ROLE TRADE_PIPELINE_ROLE
TO USER <YOUR_SNOWFLAKE_USERNAME>;