USE ROLE TRADE_PIPELINE_ROLE;
USE WAREHOUSE TRADE_WH;
USE DATABASE TRADE_DB;
USE SCHEMA MONITORING;

CREATE TABLE IF NOT EXISTS PIPELINE_RUN_LOG (
  run_id STRING,
  dag_id STRING,
  status STRING,
  started_at TIMESTAMP_TZ,
  completed_at TIMESTAMP_TZ,
  records_loaded NUMBER,
  records_rejected NUMBER,
  error_message STRING,
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
